/*Wrapper, Get created meeting Info */
/*******************************************************************************************************************
** Module Name   : CreateMeetingInfoReturn
** Description   : Wrapper, having all property required for Create Meeting info.
** Throws        : No
** Calls         : No
** Test Class    : NO
** 
** Organization  : Rainmaker Associates LLC
**
** Revision History:-
** Version  Date        Author    WO#         Description of Action
** 1.0      2013-05-16  AW                    Initial Version
******************************************************************************************************************/

public class CreateMeetingInfoReturn{
    public String joinURL;
    public String maxParticipants;
    public String uniqueMeetingId;
    public String conferenceCallInfo;
    public String meetingid;
}