/*******************************************************************************************************************
** Module Name   : GTMOrganizerInfo_UnitTest
** Description   : Test GTMOrganizerInfo Apex Class.
** Organization  : Rainmaker Associates LLC
**
** Revision History:-
** Version  Date        Author    WO#         Description of Action
** 1.0      2013-05-16  AW                    Initial Version
*********************************************************************************************************************/
@istest
public class GTMOrganizerInfo_UnitTest
{
    static TestMethod void GTMOrganizerInfo_Test()
    {
        GTMOrganizerInfo o=new GTMOrganizerInfo();
        System.assertEquals(true, true);
    }
}