global with sharing class MeetingInfo {
    	global String createTime;
        global String status;
        global String subject;
        global String startTime;
       	global String conferenceCallInfo;
        global String AcccessCode;
        global String meetingType;
        global String maxParticipants;
        global String endTime;
        global String uniqueMeetingId;
        global String meetingid;
        global String passwordRequired;
        
    }