public with sharing class ReportDataStruct {
    
    public String yearMonth {get;set;}
    public Decimal ConcreateMixes{get;set;}
    public Decimal ProcessedMaterials{get;set;}
    public Decimal RecycledProducts {get;set;}
    public Decimal RoweAggregages {get;set;}
    public Decimal SemiProcessedMaterials {get;set;}
    public Decimal StoneProducts {get;set;}
    public Decimal UnprocessedMaterials {get;set;}
    
    public Decimal ConcreateMixesf{get;set;}
    public Decimal ProcessedMaterialsf{get;set;}
    public Decimal RecycledProductsf {get;set;}
    public Decimal RoweAggregagesf {get;set;}
    public Decimal SemiProcessedMaterialsf {get;set;}
    public Decimal StoneProductsf {get;set;}
    public Decimal UnprocessedMaterialsf {get;set;}
    
    
    public Decimal ConcreateMixesQ{get;set;}
    public Decimal ProcessedMaterialsQ{get;set;}
    public Decimal RecycledProductsQ {get;set;}
    public Decimal RoweAggregagesQ {get;set;}
    public Decimal SemiProcessedMaterialsQ {get;set;}
    public Decimal StoneProductsQ {get;set;}
    public Decimal UnprocessedMaterialsQ {get;set;}

}