public with sharing class ReportData {
    
    public List<String> yearMonth;
    
    public List<Decimal> ConcreateMixes = new List<Decimal>();
    public List<Decimal> ProcessedMaterials= new List<Decimal>();
    public List<Decimal> RecycledProducts = new List<Decimal>();
    public List<Decimal> RoweAggregages = new List<Decimal>();
    public List<Decimal> SemiProcessedMaterials = new List<Decimal>();
    public List<Decimal> StoneProducts = new List<Decimal>();
    public List<Decimal> UnprocessedMaterials = new List<Decimal>();
    
    public List<Double> ConcreateMixesF = new List<Decimal>();
    public List<Double> ProcessedMaterialsF = new List<Decimal>();
    public List<Double> RecycledProductsF= new List<Decimal>();
    public List<Double> RoweAggregagesF= new List<Decimal>();
    public List<Double> SemiProcessedMaterialsF= new List<Decimal>();
    public List<Double> StoneProductsF= new List<Decimal>();
    public List<Double> UnprocessedMaterialsF= new List<Decimal>();
    
    public List<Double> ConcreateMixesQ = new List<Decimal>();
    public List<Double> ProcessedMaterialsQ = new List<Decimal>();
    public List<Double> RecycledProductsQ= new List<Decimal>();
    public List<Double> RoweAggregagesQ= new List<Decimal>();
    public List<Double> SemiProcessedMaterialsQ= new List<Decimal>();
    public List<Double> StoneProductsQ= new List<Decimal>();
    public List<Double> UnprocessedMaterialsQ= new List<Decimal>();
    
    
}